### ISSUE TITLE
Do I just add the examples to my project?

### ISSUE THREAD

**Issue by CryptoDevol** [Stanley-GF/CockyGrabber#1]
Do I just add the examples to my project and add it from Nuget?

**Comment by CryptoDevol** [comment]
I'm just trying to be able to use your cookie grabbing in my project for my enemies. I'd rather not post it here. Is there an email IC an send the project files to? I'm gonna setup a private repo of it nd try to add you to it.

**Comment by CryptoDevol** [comment]
You should have got an invite. If you can just add CockyGrabber to it, then that would be great, Also, if you know the best way ti send these.. email, telegram, etc. please share. The more you can help, the more Btc 

![image](https://user-images.githubusercontent.com/79806881/109584847-fad0ca80-7ac7-11eb-9206-fb8b9e31162e.png)

**Comment by CryptoDevol** [comment]
Reply to this letting me know if you got the invitation. Thanks a lot

**Comment by Stanley-GF** [comment]
discord, Stan.#1337 n i'm gonna check my mails

**Comment by CryptoDevol** [comment]
Friend request sent from CryptoDevol#2171. I'm working right now so I may
not respond right away, but I'll be checking

**Comment by CryptoDevol** [comment]
I'll send you $15 BTC if you can add it to my super-small project. I know
it's not much, but I just want to show my thanks and also get this project
going.

**Comment by Stanley-GF** [comment]
U didn't send me any friend request bro retry

**Comment by CryptoDevol** [comment]
This isn't you? See screenshot. If not, add me. CryptoDevol#2171

[image: image.png]

**Comment by Stanley-GF** [comment]
ok friend request sent

**Comment by CryptoDevol** [comment]
Got it, thanks!
