### ISSUE TITLE
can't use in .net4.0

### ISSUE THREAD

**Issue by qwqdanchun** [Stanley-GF/CockyGrabber#3]
Is it possible to make this project run on .net4.0.

**Comment by Stanley-GF** [comment]
i'm coding something else, in 1h-2h ok?

**Comment by qwqdanchun** [comment]
No hurry. Thank you very much

**Comment by Stanley-GF** [comment]
Ok back, you want in 4.0 right? Let me install the framework.

**Comment by Stanley-GF** [comment]
ok done, .NET Framework right ? 
[you can download here](https://www.mediafire.com/file/i0prsvknpxyofkt/CockyGrabber+-+4.0+(Compiled+++src).zip/file)

**Comment by qwqdanchun** [comment]
Many thanks ! It works well !
