### ISSUE TITLE
Is there a way to get Firefox passwords?

### ISSUE THREAD

**Issue by shakydd** [Stanley-GF/CockyGrabber#4]
I could only see passwords for Chrome, Edge and Opera - is that right?

**Comment by Stanley-GF** [comment]
Yes password & cookies but we are open for contributor, so you can purpose
new browsers, history etc :)

**Comment by shakydd** [comment]
No worries, above my skill level :-) But Cookies at least for Firefox are useful and all the history\password\cookies for Chrome, Edge and Opera is excellent so thanks and keep up the good work.
